name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push FireSnapshot.podspec
