name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@preview
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'
      - name: Setup
        run: make
      - name: Install firebase-tools
        run: npm install -g firebase-tools@latest && firebase setup:emulators:firestore
      - name: Run Test
        run: scripts/test.sh
